### ISSUE TITLE
Reformat the tests to run on only one open Blog browser window

### ISSUE THREAD

**Issue by vankatabe** [vankatabe/Feijoa#18]
Present condition is every test fires-up a new Blog window and closes it at the end of the test

**Comment by vankatabe** [comment]
Locally it runs, but not on CI server.
Error:
System.ArgumentNullException : Argument 'url' cannot be null.
Parameter name: value
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at Blog.UI.Tests.BasePage.NavigateTo(String url) in C:\BuildAgent\work\4d2cc47ae117f2f8\Blog.UI.Tests\BasePage.cs:line 42
   at Blog.UI.Tests.HomePageTests.CheckWebSiteLoad_EnterBlogURL_OpenBlogHomePage() in C:\BuildAgent\work\4d2cc47ae117f2f8\Blog.UI.Tests\HomePageTests.cs:line 61

**Comment by vankatabe** [comment]
seems that the error is somewhere else.
