### ISSUE TITLE
URL argument is null on CI server - happened after working on #18

### ISSUE THREAD

**Issue by vankatabe** [vankatabe/Feijoa#20]
Locally it runs, but not on CI server.
Error:
System.ArgumentNullException : Argument 'url' cannot be null.
Parameter name: value
at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
at Blog.UI.Tests.BasePage.NavigateTo(String url) in C:\BuildAgent\work\4d2cc47ae117f2f8\Blog.UI.Tests\BasePage.cs:line 42
at Blog.UI.Tests.HomePageTests.CheckWebSiteLoad_EnterBlogURL_OpenBlogHomePage() in C:\BuildAgent\work\4d2cc47ae117f2f8\Blog.UI.Tests\HomePageTests.cs:line 61

**Comment by vankatabe** [comment]
I didnt build the project before Commit and the .dll was the old one, that's why it wasn;t working.
